version: '3.5'
services:
  app:
    build: .
    container_name:
      deploy-gradle-app
    ports:
      - 8181:8080
    command:  sh -c "./gradlew bootRun"
    restart: on-failure 
  nginx:
    image:
      nginx:mainline
    ports:
      - 80:81
    volumes:
      - ./deploy-gradle.conf:/etc/nginx/conf.d/deploy-gradle.conf
      #- ./default.conf:/etc/nginx/conf.d/default.conf
    container_name:
      deploy-gradle-nginx
    depends_on:
      - app
    restart: on-failure 